In [1]:
import numpy as np
arr = np.load('ex_array.npy')

### Reshaping
Often, we want to arrange an array in a different shape. For this purpose, we can use the `reshape` method.

In [2]:
mat_1 = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
mat_1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
mat_1.shape

(3, 2)

The simplest example of this is flattening a matrix:

In [5]:
mat_1.reshape(6)

array([1, 2, 3, 4, 5, 6])

This is so popular that there is a special function for it:

In [6]:
mat_1.flatten()

array([1, 2, 3, 4, 5, 6])

In [7]:
mat_1

array([[1, 2],
       [3, 4],
       [5, 6]])

As you can see, the `reshape` method iterates through rows before columns. What will be the output of `mat_1.reshape(2,3)`?

In [8]:
mat_3 = mat_1.reshape(2, 3)
mat_3

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
mat_3.shape

(2, 3)

In [10]:
vec_1 = np.array([1,2,3,4])
vec_1.reshape(2,2)

array([[1, 2],
       [3, 4]])

## Exercises
1. What will be the output of the following piece of code:
```
vec_1 = np.array([1,2,3,4])
vec_1.reshape(2,2)

### array([[1,2]
           [3,4]])

```
2. Consider the example array we considered in the lesson (it is loaded into this notebook in the first line together with the numpy import). As a reminder the first two dimensions referred to two different conditions for the neural data and ten repetitions of the measurements. Suppose you didn't care about the differences between those conditions and simply wanted to consider the total of 20 trials as repetitions, thus considering a matrix with 20 repetitions, 50 neurons, and 2000 timesteps. How could you reshape the array in this manner?

In [23]:
### I could not figure out how to solve the above problem #2

## Transposing

`mat_1.T` transposes the matrix flipping rows and columns.

In [24]:
mat_1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
mat_1.T

array([[1, 3, 5],
       [2, 4, 6]])

For higher-dimensional arrays, the `transpose` method allows you to specify the new order of the axes. You are doing so by providing a tuple of integers. If you specify axis 2 in the first entry of that tuple for instance, what used to be axis 2 now becomes axis 0 and so on:

In [26]:
arr.shape

(2, 10, 50, 2000)

In [31]:
arr_t = arr.transpose((2, 0, 1, 3))
arr_t.shape

(50, 2, 10, 2000)

## Questions
What is going to be the output shape of the following commands?
```
arr_t = arr.transpose((1,3,2,0))

10, 2000, 50, 2
arr_t = arr.transpose((2,1,0,3))

50, 10, 2, 2000
arr_t = arr.transpose((0,1,2,3))

2, 10, 50, 1000

```
Try to predict the shape and then test it by running the commands.

In [34]:
arr_t = arr.transpose((0,1,2,3))
arr_t.shape



(2, 10, 50, 2000)

### Broadcasting

In general you cannot add two matrices with different shapes:

In [35]:
mat_1.shape

(3, 2)

In [36]:
mat_3 = np.array([
    [1,2,3],
    [1,2,3]
])
mat_3.shape

(2, 3)

In [37]:
mat_1+mat_3

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

Elementwise operations can work between two arrays with unequal shapes:
- If they match everywhere except where one of them has a dimension of length 1
- If they have an unequal number of dimensions, the array with fewer dimensions is appended dimensions of length 1 in the beginning.

In [69]:
mat_4 = np.array([
    [1,2]
])
mat_5 = np.array([
    [[1,2]],
    [[3,4]],
    [[5,6]]
])
mat_4_plus_5 = mat_4+mat_5
mat_4_plus_5

array([[[2, 4]],

       [[4, 6]],

       [[6, 8]]])

In [68]:
mat_4_plus_5.shape

(3, 1, 2)

In [71]:
mat_4.shape

(1, 2)

The same thing is true for matrices with one column or other elementwise operations.

In [72]:
divisor = np.array([[2], [1], [1]])

In [73]:
divisor.shape

(3, 1)

In [40]:
divisor

array([[2],
       [1],
       [1]])

In [74]:
mat_1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [75]:
mat_1 / divisor

array([[0.5, 1. ],
       [3. , 4. ],
       [5. , 6. ]])

In [47]:
vec_1 = np.array([1, 2])
vec_1

array([1, 2])

In [48]:
vec_1.shape

(2,)

In [45]:
mat_1.shape

(3, 2)

In [49]:
vec_1+mat_1

array([[2, 4],
       [4, 6],
       [6, 8]])

### Questions

Below we're creating arrays with different shapes. Try predicting for each if elementwise addition would work, what shape the resulting array would have, then try it out and see if you were correct.

In [76]:
arr_1 = np.ones((3,2))
arr_2 = np.ones((2,3))

arr_1+arr_2

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [81]:
arr_1 = np.ones((4,1,5))
arr_2 = np.ones((4,6,5))

arr_1+arr_2

array([[[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]])

In [92]:
arr_1 = np.ones((4,1,5))
arr_2 = np.ones((4,6,1))

arr_1+arr_2

array([[[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]])

In [84]:
arr_1 = np.ones((4,3,5))
arr_2 = np.ones((3,5))

arr_1+arr_2

array([[[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]])

In [85]:
arr_1 = np.ones((4,3,5))
arr_2 = np.ones((4,3))

arr_1+arr_2

ValueError: operands could not be broadcast together with shapes (4,3,5) (4,3) 

### Boolean indexing

Do you remember how to create an array that has True values for any entry smaller than 5 and False value for all other entries?

In [93]:
vec = np.arange(10)

In [94]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
vec < 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [96]:
selector = vec < 5
selector

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

You can use these boolean arrays to subset the corresponding true values.

In [97]:
vec

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
vec[selector]

array([0, 1, 2, 3, 4])

In [99]:
vec[vec<5]

array([0, 1, 2, 3, 4])

You can do the same with matrices:

In [100]:
mat_1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [101]:
mat_1 >= 3

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [134]:
mat_1[mat_1 >= 3]


array([3, 4, 5, 6])

### Questions
- Consider the example matrix from above and subset all entries with values between 2 and 4.

In [104]:
mat_1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [151]:
mat_1[(mat_1 >= 2) & (mat_1 <= 4)]


array([2, 3, 4])

In [152]:
### I got this to work by looking up how to use a boolean "and" with numpy, which told me to use "&". 
# Not sure how I would do this otherwise