# Error handling
## Errors

By now, we have seen several pieces of code that have failed to run. In that case, Python does not only raise an error, but also specifies what exactly went wrong.

In [1]:
# A syntax error indicates that your code is not properly formatted:
a = 2
print(a+3

SyntaxError: incomplete input (495188828.py, line 3)

In [2]:
# A type error indicates that a function received an input of the wrong type
a = '2'
print(a+3)

TypeError: can only concatenate str (not "int") to str

In [3]:
# An index error suggests that it is not possible to index an object in the attempted way.
a = [2, 3]
a[3]

IndexError: list index out of range

You can return errors yourself using the command `raise`:

In [7]:
a = 3
if a == 3:
  raise ValueError('a should not be three')

ValueError: a should not be three

### Exercise
Write a function `integer_add` that takes two arguments and adds them together. If either of the arguments are not integers, it should raise an error. What is the correct error for this issue?

In [45]:
def integer_add(a,b):
    sum = a+b
    if type(a) != int and type(b) != int:
        return sum
    elif type(a) is not int or type(b) is not int:
        raise ValueError('issue')


In [40]:
type(2.0)

float

In [41]:
integer_add(1,2)

3

In [46]:
integer_add(1.5,2)

ValueError: issue

## Try / Except


`try` tries the code in the `try` codeblock, and if it gives an error, runs code in an `except` code block. Best practice is to specify the errors you expect in the `except` statement so that you don't accidentally allow an unexpected error to go by unreported and unnoticed.

For example, lets say that we want to count the number of occurrences of each letter in a given word -- for this example we will use abracadabra, but we want our code to work on any word.

We might decide to do this using a dictionary where the keys are the letters and the values are the number of times that letter has occurred. We only want to have letters that do occur in the word as keys in our dictionary.

In [47]:
word = "abracadabra"

letter_counts = {
    'a': 0
}
for letter in word: # we can loop through strings like lists or tuples.
  letter_counts[letter]+=1 # add one to the value at key letter

KeyError: 'b'

In [48]:
word = "abracadabra"


letter_counts = {}
for letter in word:
  try:
    letter_counts[letter]+=1
  except KeyError: # we specify the type of error we expect here
    letter_counts[letter] = 1

print(letter_counts)

{'a': 5, 'b': 2, 'r': 2, 'c': 1, 'd': 1}


See below for why it is important to specify the type of error you expect. Since we specified the type of error we expected and got a different error, we still find out that there is an error, and can take precautions to make sure we don't, for example, overwrite important info.

In [ ]:
word = "abracadabra"


letter_counts = {}
letter_counts['a'] = "important info that should not be overwritten" # something unexpected as a value
for letter in word:
  try:
    letter_counts[letter]+=1
  except KeyError: # we specify the type of error we expect here
    letter_counts[letter] = 1

print(letter_counts)

What happens if you do not specify KeyError after `except` and just write `except:`?

Try modifying below.

In [49]:
word = "abracadabra"


letter_counts = {}
letter_counts['a'] = "important info that should not be overwritten" # something unexpected as a value
for letter in word:
  try:
    letter_counts[letter]+=1
  except: # we specify the type of error we expect here
    letter_counts[letter] = 1

print(letter_counts)

{'a': 5, 'b': 2, 'r': 2, 'c': 1, 'd': 1}


### Exercise:
Use try/except to write code that takes numbers a and b and prints a/b. If it gets an error (for example b is 0), it should instead print "Cannot divide by zero". Try your code with a few different choices of a and b to make sure it works correctly.

*Hint* To find out what error you should be expecting try dividing something by 0 to see what error you get.

In [94]:
def test1(a,b):
    try:
        result = a/b
        if a > 0 and b > 0:
            return result
    except ZeroDivisionError:
        print('cannot divide by zero')

In [92]:
test1(0,2)

# Numpy

We often want to work with arrays of numerical data, for example a list of firing rates. We can store such data using basic Python, more specifically as a list of numbers:

In [83]:
lst_1 = [25, 20, 40, 5] 

But these lists are missing a lot of functionality that we find useful for handling numerical data. (You may be used to these from Matlab or R.) For example, suppose you want to multiply each number by 2. We may want the following command to work:

In [84]:
2*lst_1

[25, 20, 40, 5, 25, 20, 40, 5]

Yet its output is not what we are looking for. This is because lists are not *vectorized*: they do not assume that operations should be applied elementwise. Instead we would have to use a command like the one below:

In [85]:
lst_2 = [lst_1[i]*2 for i in range(4)]
lst_2

[50, 40, 80, 10]

To address this and other issue that arise in handling numerical data in Python, we can use `numpy`, which stands for numerical data in Python.

So far, we have exclusively used Python's base functionality. `numpy` is the first example of a package that has been contributed by external users and has to be installed manually. It is, however, integral to Python for basically anyone working with numerical data.

In [6]:
import numpy as np

## One-dimensional arrays: Vectors
The central object of interest for numpy is an *array*, which refers to rectangular data (more on this later). The simplest case of an array is a one-dimensional one, a vector. You can create a vector from a list:

In [96]:
vec_1 = np.array(lst_1)

In [97]:
vec_1

array([25, 20, 40,  5])

In [98]:
type(vec_1)

numpy.ndarray

We can also turn a vector back into a list:

In [99]:
list(vec_1)

[25, 20, 40, 5]

Using the numpy array, we can now perform mathematical operations in the way we would like (and perhaps expect from e.g. Matlab).

In [100]:
vec_2 = 2*vec_1
vec_2

array([50, 40, 80, 10])

In [101]:
vec_1+vec_2

array([ 75,  60, 120,  15])

In contrast, what happens if we add two lists?

In [102]:
lst_1 + lst_2

[25, 20, 40, 5, 50, 40, 80, 10]

### Differences between lists and vectors
Both lists and vectors can be indexed and we can easily transform an array into a list and vice versa. What are some of their differences?
#### Elementwise operations
We have already covered that arrays have elementwise operations whereas lists do not.
#### Each element must have the same type
Lists can consist of elements with different types:

In [103]:
lst_3 = ['a', 5]
lst_3

['a', 5]

An array, on the other hand, will always have the same data type for each of its elements. If a list with unequal types is converted to an array all its elements are converted to the same data type.

In [104]:
vec_3 = np.array(lst_3)
vec_3

array(['a', '5'], dtype='<U21')

<U21 is the data type corresponding to strings. You usually don't want to rely on this automatic casting functionality and should try to avoid it.

In [ ]:
type(vec_3)

How can you print out the type of this vector? Note that `type(vec_3)` gives you the type of the entire object which is a numpy array. Rather you want the type of the individual elements. Try using the autocomplete function to find out.

*Hint* look at what the type information was called above.

In [107]:
vec_1.dtype

dtype('int64')

We do we not need parentheses after `dtype`? This is because `dtype` is not function, but rather a new type of Python object called an *attribute*. We will get to know them in more depth in a later lesson.

The order of types is:
- object (general Python objects)
- string
- float
- int
- boolean

### Question 1

- Create a numpy array with the elements 3, 7, 10 and divide each element by two
- Create a new array `vec_4` that is the elementwise multiplication of `vec_1` and `vec_2`.
- Create an array `vec_5` that has a `True` value wherever `vec_1` is smaller than or equal to `20` and a `False` value otherwise. *Hint:* This should be possible in a one liner.

In [108]:
a = np.array([3,7,10])
b = a/2
b

array([1.5, 3.5, 5. ])

In [110]:
vec_4 = vec_1*vec_2
vec_4

array([1250,  800, 3200,   50])

In [119]:
vec_5 = np.array([true for x in vec_1([x]) if x<= 20])

NameError: name 'x' is not defined

## Two-dimensional arrays: Matrices
Rectangular data in two dimensions is often called a matrix: it consists of observations organized by rows and columns. Basic Python would allow us to store such data using a list of lists:

In [2]:
lst_1 = [
    [1, 2],
    [3, 4],
    [5, 6]
]
lst_1

[[1, 2], [3, 4], [5, 6]]

Yet the already tedious process of computing elementwise operations quickly becomes infeasible in this context. If wanted to multiply each element by two we would have to iterate over the outer list and then the inner set of lists.

In [3]:
lst_2 = [
    [2*it2 for it2 in it] for it in lst_1
]
lst_2

[[2, 4], [6, 8], [10, 12]]

Again we can turn the list of lists into a matrix simply by applying `np.array`:

In [7]:
mat_1 = np.array(lst_1)
mat_1

array([[1, 2],
       [3, 4],
       [5, 6]])

Now we can apply vectorized operations as previously:

In [8]:
mat_2 = 2*mat_1
mat_2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

How can you find out the number of rows and columns of the matrix? Try googling or exploring the methods using the autocomplete function.

In [123]:
mat_1.shape

(3, 2)

Importantly, numpy, by default, uses elementwise computations. So `*` results in elementwise multiplication, not matrix multiplication.

In [124]:
mat_1*mat_2

array([[ 2,  8],
       [18, 32],
       [50, 72]])

You can run matrix multiplication by using the `@` operator.

In [125]:
mat_3 = np.array([[1,2],[3,4]])
mat_1@mat_3

array([[ 7, 10],
       [15, 22],
       [23, 34]])

### Saving arrays
We can save arrays using `np.save`.

In [12]:
np.save('mat_1.npy', mat_1)

SyntaxError: invalid syntax (2135079249.py, line 1)

In [10]:
mat_1_copy = np.load('mat_1.npy')

In [11]:
mat_1_copy

array([[1, 2],
       [3, 4],
       [5, 6]])

## Higher-dimensional arrays

We now load some simulated data, which is stored in the file `ex_array.npy`. Try assigning the data in that file to the variable `arr`.

In [13]:
arr = np.load('ex_array.npy')

Suppose you know that what is stored in this data are spike rates of fifty different neurons for two different conditions and ten repeated measurements. Spike rates are recorded every second for 2000 seconds. How can you figure out how this data is represented in the array?

In [130]:
arr.shape

(2, 10, 50, 2000)

In [131]:
arr.ndim

4

Whereas a vector has one dimension and a matrix has two dimensions, `arr` has four dimensions: the first one specifies the condition, the second one the trial, the third one the neuron, and the fourth one the timepoint. We can also create higher-dimensional arrays directly:

In [132]:
arr_2 = np.array([
    [[2,4,6],
     [1,3,5]],
    [[0.5,1,2],
     [0.75, 1, 1.25]]
])

What is `arr_2.ndim` and `arr_2.shape`?

In [133]:
arr_2.ndim

3

In [134]:
arr_2.shape

(2, 2, 3)

### Data must be rectangular
Importantly numpy only allows for rectangular data. What happens if you create an array from a list of lists with unequal length?

In [135]:
mat = np.array([[1,2],[3]])

/var/folders/t3/980hh_n92cxgv43wtqfh9nmw0000gn/T/ipykernel_25232/2922253680.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  mat = np.array([[1,2],[3]])


In [ ]:
mat

array([list([1, 2]), list([3])], dtype=object)

### Broadcasting

In general you cannot add two matrices with different shapes:

In [14]:
mat_1.shape

(3, 2)

In [16]:
mat_3 = np.array([
    [1,2,3],
    [1,2,3]
])

In [17]:
mat_1+mat_3

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

Elementwise operations can work between two arrays with unequal shapes:
- If they match everywhere except where one of them has a dimension of length 1
- If they have an unequal number of dimensions, the array with fewer dimensions is appended dimensions of length 1 in the beginning.

In [15]:
np.array([
    [1,2]
]) + np.array([
    [1,2],
    [3,4],
    [5,6]
])

array([[2, 4],
       [4, 6],
       [6, 8]])

The same thing is true for matrices with one column or other elementwise operations.

In [18]:
divisor = np.array([[2], [1], [1]])

In [19]:
divisor.shape

(3, 1)

In [20]:
mat_1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
mat_1 / divisor

array([[0.5, 1. ],
       [3. , 4. ],
       [5. , 6. ]])

In [22]:
vec_4 = np.array([1, 2])

In [23]:
vec_4.shape

(2,)

In [24]:
vec_4+mat_1

array([[2, 4],
       [4, 6],
       [6, 8]])

### Creating some arrays

In [25]:
np.linspace(0, 1, 21)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

In [26]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [28]:
np.ones((4, 2, 3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

### Question 2

Below we're creating arrays with different shapes. Try predicting for each if elementwise addition would work, what shape the resulting array would have, then try it out and see if you were correct.

In [29]:
arr_1 = np.ones((3,2))
arr_2 = np.ones((2,3))

In [30]:
arr_1 = np.ones((4,1,5))
arr_2 = np.ones((4,6,5))

In [31]:
arr_1 = np.ones((4,1,5))
arr_2 = np.ones((4,6,1))

In [32]:
arr_1 = np.ones((4,3,5))
arr_2 = np.ones((3,5))

In [33]:
arr_1 = np.ones((4,3,5))
arr_2 = np.ones((4,3))

## Summary operations

Summary operations allow you to collapse an array according to a certain summary statistic. For instance, we may want to compute the overall mean firing rate in our experimental data:

In [141]:
arr.mean()

0.8717270073789571

You can also specify the axis along we want to average. For instance, maybe we want to average firing rates across individual trials:

In [142]:
arr.shape

(2, 10, 50, 2000)

In [145]:
arr_across_trials = arr.mean(axis=1)
arr_across_trials

array([[[0.65972936, 0.68679441, 0.68199004, ..., 0.96912439,
         1.07270512, 0.84568177],
        [0.79611248, 0.99935367, 0.88531804, ..., 0.50904864,
         0.3364558 , 0.4932102 ],
        [1.00938778, 1.30849305, 0.95961269, ..., 0.67265484,
         0.94855162, 0.57360145],
        ...,
        [0.32410045, 0.60430154, 0.59851933, ..., 0.43082814,
         0.35448484, 0.60595627],
        [2.20282076, 2.10202105, 1.72845273, ..., 2.40318232,
         2.62285072, 2.47028176],
        [0.77735322, 1.2437595 , 1.09964378, ..., 1.38810799,
         1.48371474, 1.22155473]],

       [[0.29366721, 0.40403176, 0.32066067, ..., 1.11915401,
         0.79285423, 1.20313501],
        [0.54035301, 0.7392684 , 0.70751494, ..., 1.3894037 ,
         1.30790281, 1.4672015 ],
        [0.62631555, 0.49423944, 0.59660195, ..., 0.82260387,
         0.99906975, 0.56779008],
        ...,
        [0.60475668, 0.75494216, 0.66881441, ..., 0.33957372,
         0.47778094, 0.5476308 ],
        [0.4

In [144]:
arr_across_trials.shape

(2, 50, 2000)

The `keepdims` argument means that you don't remove the dimensions you're averaging over, but rather set their length to 1:

In [146]:
arr_across_trials = arr.mean(axis=1, keepdims=True)

In [147]:
arr_across_trials.shape

(2, 1, 50, 2000)

You can average across multiple axes as well. For instance, maybe you want to average across both trials and time:

In [148]:
arr_across_trials_and_time = arr.mean(axis=(1,3))

In [149]:
arr_across_trials_and_time.shape

(2, 50)

### Question 3

- What is the average firing rate across all neurons, times, and trials for each condition?
- (Advanced.) Subtract the average firing rate per time across all neurons, trials, and conditions from the original array.

In [156]:
arr_across_trials_time_neurons = arr.mean(axis=(1,2,3), keepdims=True)
arr_across_trials_time_neurons.shape


(2, 1, 1, 1)

## Indexing

Indexing in vectors works just as in lists:

In [157]:
vec_1

array([25, 20, 40,  5])

In [158]:
vec_1[0]

25

For matrices and higher-dimensional arrays, a single index selects a single row:

In [159]:
mat_1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [160]:
mat_1[0]

array([1, 2])

In [161]:
mat_1[0][1]

2

Instead of using two brackets, you can also separate the row and column index by a comma:

In [162]:
# The following two lines of code are equivalent
print(mat_1[0][0])
print(mat_1[0,0])

1
1


### Slicing

Slicing is a useful way of extracting more than one element. In particular, `j:k` extracts the elements j,...,k-1:

In [163]:
vec = np.arange(10)
print(vec)

[0 1 2 3 4 5 6 7 8 9]


In [164]:
vec[3:7]

array([3, 4, 5, 6])

We can leave either end of the range away and it will default to the beginning and the end of the list, respectively.

In [165]:
vec[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [166]:
vec[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [167]:
vec[:] # What do you think this will do?

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

You can therefore also use the colon to select all rows of a matrix and specific columns.

In [168]:
mat_1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [169]:
mat_1[:,0]

array([1, 3, 5])

You can add another colon to specify a step size, similarly to how you would use these three arguments in `range`.

In [171]:
vec

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [170]:
vec[3:7:2]

array([3, 5])

We could still leave away the beginning or the end of the slice:

In [172]:
vec[::2]

array([0, 2, 4, 6, 8])

### Question 4
Predict the output of the following commands:

In [173]:
vec[:4]
# 0,1,2,3

array([0, 1, 2, 3])

In [174]:
vec[5:9:2]
#5,7

array([5, 7])

In [175]:
vec[:7:2]
#0,2,4,6

array([0, 2, 4, 6])

In [176]:
vec[2::2]
#2,4,6,8

array([2, 4, 6, 8])

### Boolean indexing

Do you remember how to create an array that is true if and only if `vec` is smaller than 5?

In [177]:
vec

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [178]:
selector = vec <= 5
selector

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False])

You can use these boolean arrays to subset the corresponding true values.

In [179]:
vec

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [180]:
vec[selector]

array([0, 1, 2, 3, 4, 5])

In [181]:
vec[vec<=5]

array([0, 1, 2, 3, 4, 5])

You can do the same with matrices:

In [182]:
mat_1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [185]:
mat_1 >= 3

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [186]:
mat_1[mat_1 >= 3]

array([3, 4, 5, 6])

### Questions 5
- Consider the example matrix from above and subset all entries with values between 0.4 and 0.8.